// Generated by tools/generate_gem_catalog.py. Do not edit.
package com.kinderman.sdo.domain.catalog

import com.kinderman.sdo.domain.model.ItemEffect
import com.kinderman.sdo.domain.model.ItemEffectCondition
import com.kinderman.sdo.domain.model.ItemEffectType
import com.kinderman.sdo.domain.model.ItemPart

internal enum class GemTier { MINOR, MAJOR }
internal data class GemDefinition(val part: ItemPart, val tier: GemTier, val effect: ItemEffect)
internal object GeneratedGemCatalog {
    val entries = listOf(
        GemDefinition(
            ItemPart("gema_menor_conhecimento_aleatorio", "Gema Menor de Conhecimento", "Gema", 2, 45, effect = "+1 em um Conhecimento aleatório, definido permanentemente ao instalar a gema."),
            GemTier.MINOR,
            ItemEffect("gema_menor_conhecimento_aleatorio", ItemEffectType.KNOWLEDGE, 1, "*", ItemEffectCondition.WIELDED, "+1 em um Conhecimento aleatório, definido permanentemente ao instalar a gema."),
        ),
        GemDefinition(
            ItemPart("gema_atributo_for", "Gema de Força", "Gema", 4, 150, effect = "+1 em Força enquanto a arma estiver empunhada."),
            GemTier.MAJOR,
            ItemEffect("gema_atributo_for", ItemEffectType.ATTRIBUTE, 1, "FOR", ItemEffectCondition.WIELDED, "+1 em Força enquanto a arma estiver empunhada."),
        ),
        GemDefinition(
            ItemPart("gema_atributo_vig", "Gema de Vigor", "Gema", 4, 150, effect = "+1 em Vigor enquanto a arma estiver empunhada."),
            GemTier.MAJOR,
            ItemEffect("gema_atributo_vig", ItemEffectType.ATTRIBUTE, 1, "VIG", ItemEffectCondition.WIELDED, "+1 em Vigor enquanto a arma estiver empunhada."),
        ),
        GemDefinition(
            ItemPart("gema_atributo_agi", "Gema de Agilidade", "Gema", 4, 150, effect = "+1 em Agilidade enquanto a arma estiver empunhada."),
            GemTier.MAJOR,
            ItemEffect("gema_atributo_agi", ItemEffectType.ATTRIBUTE, 1, "AGI", ItemEffectCondition.WIELDED, "+1 em Agilidade enquanto a arma estiver empunhada."),
        ),
        GemDefinition(
            ItemPart("gema_atributo_pod", "Gema de Poder", "Gema", 4, 150, effect = "+1 em Poder enquanto a arma estiver empunhada."),
            GemTier.MAJOR,
            ItemEffect("gema_atributo_pod", ItemEffectType.ATTRIBUTE, 1, "POD", ItemEffectCondition.WIELDED, "+1 em Poder enquanto a arma estiver empunhada."),
        ),
        GemDefinition(
            ItemPart("gema_atributo_int", "Gema de Intelecto", "Gema", 4, 150, effect = "+1 em Intelecto enquanto a arma estiver empunhada."),
            GemTier.MAJOR,
            ItemEffect("gema_atributo_int", ItemEffectType.ATTRIBUTE, 1, "INT", ItemEffectCondition.WIELDED, "+1 em Intelecto enquanto a arma estiver empunhada."),
        ),
        GemDefinition(
            ItemPart("gema_atributo_car", "Gema de Carisma", "Gema", 4, 150, effect = "+1 em Carisma enquanto a arma estiver empunhada."),
            GemTier.MAJOR,
            ItemEffect("gema_atributo_car", ItemEffectType.ATTRIBUTE, 1, "CAR", ItemEffectCondition.WIELDED, "+1 em Carisma enquanto a arma estiver empunhada."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_aurora_fio", "Fio de Aurora", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_aurora_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_aurora_guarda", "Guarda de Aurora", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_aurora_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_aurora_pulso", "Pulso de Aurora", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_aurora_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_aurora_veu", "Véu de Aurora", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_aurora_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_aurora_eco", "Eco de Aurora", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_aurora_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_basalto_fio", "Fio de Basalto", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_basalto_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_basalto_guarda", "Guarda de Basalto", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_basalto_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_basalto_pulso", "Pulso de Basalto", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_basalto_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_basalto_veu", "Véu de Basalto", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_basalto_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_basalto_eco", "Eco de Basalto", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_basalto_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_carmesim_fio", "Fio de Carmesim", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_carmesim_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_carmesim_guarda", "Guarda de Carmesim", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_carmesim_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_carmesim_pulso", "Pulso de Carmesim", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_carmesim_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_carmesim_veu", "Véu de Carmesim", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_carmesim_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_carmesim_eco", "Eco de Carmesim", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_carmesim_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_cobalto_fio", "Fio de Cobalto", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_cobalto_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_cobalto_guarda", "Guarda de Cobalto", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_cobalto_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_cobalto_pulso", "Pulso de Cobalto", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_cobalto_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_cobalto_veu", "Véu de Cobalto", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_cobalto_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_cobalto_eco", "Eco de Cobalto", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_cobalto_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_crepusculo_fio", "Fio de Crepúsculo", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_crepusculo_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_crepusculo_guarda", "Guarda de Crepúsculo", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_crepusculo_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_crepusculo_pulso", "Pulso de Crepúsculo", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_crepusculo_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_crepusculo_veu", "Véu de Crepúsculo", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_crepusculo_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_crepusculo_eco", "Eco de Crepúsculo", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_crepusculo_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_eter_fio", "Fio de Éter", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_eter_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_eter_guarda", "Guarda de Éter", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_eter_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_eter_pulso", "Pulso de Éter", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_eter_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_eter_veu", "Véu de Éter", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_eter_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_eter_eco", "Eco de Éter", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_eter_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_ferrugem_fio", "Fio de Ferrugem", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_ferrugem_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_ferrugem_guarda", "Guarda de Ferrugem", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_ferrugem_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_ferrugem_pulso", "Pulso de Ferrugem", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_ferrugem_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_ferrugem_veu", "Véu de Ferrugem", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_ferrugem_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_ferrugem_eco", "Eco de Ferrugem", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_ferrugem_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_marfim_fio", "Fio de Marfim", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_marfim_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_marfim_guarda", "Guarda de Marfim", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_marfim_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_marfim_pulso", "Pulso de Marfim", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_marfim_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_marfim_veu", "Véu de Marfim", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_marfim_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_marfim_eco", "Eco de Marfim", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_marfim_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_tempestade_fio", "Fio de Tempestade", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_tempestade_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_tempestade_guarda", "Guarda de Tempestade", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_tempestade_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_tempestade_pulso", "Pulso de Tempestade", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_tempestade_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_tempestade_veu", "Véu de Tempestade", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_tempestade_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_tempestade_eco", "Eco de Tempestade", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_tempestade_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_vidro_fio", "Fio de Vidro", "Gema", 3, 90, effect = "Converte parte do impacto em dano mágico sutil."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_vidro_fio", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "Converte parte do impacto em dano mágico sutil."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_vidro_guarda", "Guarda de Vidro", "Gema", 3, 90, effect = "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
            GemTier.MINOR,
            ItemEffect("gema_aprimoramento_vidro_guarda", ItemEffectType.DURABILITY, 1, "durability", ItemEffectCondition.WIELDED, "Reduz em 1 a primeira perda de Durabilidade de cada cena."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_vidro_pulso", "Pulso de Vidro", "Gema", 6, 400, effect = "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_vidro_pulso", ItemEffectType.GEM_POWER, 0, "combat_pulse", ItemEffectCondition.WIELDED, "Uma vez por cena, após acertar, empurre o alvo 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_vidro_veu", "Véu de Vidro", "Gema", 6, 400, effect = "Uma vez por cena, receba +2 Esquiva contra um ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_vidro_veu", ItemEffectType.GEM_POWER, 0, "combat_guard", ItemEffectCondition.WIELDED, "Uma vez por cena, receba +2 Esquiva contra um ataque."),
        ),
        GemDefinition(
            ItemPart("gema_aprimoramento_vidro_eco", "Eco de Vidro", "Gema", 6, 400, effect = "Uma vez por cena, repita o menor dado de dano do ataque."),
            GemTier.MAJOR,
            ItemEffect("gema_aprimoramento_vidro_eco", ItemEffectType.GEM_POWER, 0, "combat_echo", ItemEffectCondition.WIELDED, "Uma vez por cena, repita o menor dado de dano do ataque."),
        ),
    )
    fun effect(id: String) = entries.firstOrNull { it.part.id == id }?.effect
}
