// Generated by tools/generate_gem_catalog.py. Do not edit.
package com.kinderman.sdo.domain.catalog

import com.kinderman.sdo.domain.model.ItemEffect
import com.kinderman.sdo.domain.model.ItemEffectCondition
import com.kinderman.sdo.domain.model.ItemEffectType
import com.kinderman.sdo.domain.model.ItemPart

internal enum class GemTier { COMMON, UNCOMMON, RARE, ANCESTRAL }
internal data class GemDefinition(val part: ItemPart, val tier: GemTier, val effect: ItemEffect)
internal object GeneratedGemCatalog {
    val entries = listOf(
        GemDefinition(
            ItemPart("gema_forca", "Gema de Força", "Gema", 2, 45, durability = 4, effect = "+1 em Força.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_forca", ItemEffectType.ATTRIBUTE, 1, "FOR", ItemEffectCondition.WIELDED, "+1 em Força."),
        ),
        GemDefinition(
            ItemPart("gema_vigor", "Gema de Vigor", "Gema", 2, 45, durability = 4, effect = "+1 em Vigor.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_vigor", ItemEffectType.ATTRIBUTE, 1, "VIG", ItemEffectCondition.WIELDED, "+1 em Vigor."),
        ),
        GemDefinition(
            ItemPart("gema_agilidade", "Gema de Agilidade", "Gema", 3, 90, durability = 5, effect = "+1 em Agilidade.", materialTier = "UNCOMMON", characterCreationVisible = true),
            GemTier.UNCOMMON,
            ItemEffect("gema_agilidade", ItemEffectType.ATTRIBUTE, 1, "AGI", ItemEffectCondition.WIELDED, "+1 em Agilidade."),
        ),
        GemDefinition(
            ItemPart("gema_poder", "Gema de Poder", "Gema", 5, 250, durability = 6, effect = "+1 em Poder.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_poder", ItemEffectType.ATTRIBUTE, 1, "POD", ItemEffectCondition.WIELDED, "+1 em Poder."),
        ),
        GemDefinition(
            ItemPart("gema_intelecto", "Gema de Intelecto", "Gema", 3, 90, durability = 5, effect = "+1 em Intelecto.", materialTier = "UNCOMMON", characterCreationVisible = true),
            GemTier.UNCOMMON,
            ItemEffect("gema_intelecto", ItemEffectType.ATTRIBUTE, 1, "INT", ItemEffectCondition.WIELDED, "+1 em Intelecto."),
        ),
        GemDefinition(
            ItemPart("gema_carisma", "Gema de Carisma", "Gema", 5, 250, durability = 6, effect = "+1 em Carisma.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_carisma", ItemEffectType.ATTRIBUTE, 1, "CAR", ItemEffectCondition.WIELDED, "+1 em Carisma."),
        ),
        GemDefinition(
            ItemPart("gema_saber_errante", "Gema de Saber Errante", "Gema", 2, 45, durability = 4, effect = "+1 em um Conhecimento sorteado ao receber a gema.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_saber_errante", ItemEffectType.KNOWLEDGE, 1, "*", ItemEffectCondition.WIELDED, "+1 em um Conhecimento sorteado ao receber a gema."),
        ),
        GemDefinition(
            ItemPart("gema_ourives", "Gema de Ourives", "Gema", 3, 90, durability = 5, effect = "+2 em Ourivesaria.", materialTier = "UNCOMMON", characterCreationVisible = true),
            GemTier.UNCOMMON,
            ItemEffect("gema_ourives", ItemEffectType.KNOWLEDGE, 2, "INT:Ourivesaria", ItemEffectCondition.WIELDED, "+2 em Ourivesaria."),
        ),
        GemDefinition(
            ItemPart("gema_engenho", "Gema de Engenho", "Gema", 5, 250, durability = 6, effect = "+2 em Engenharia.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_engenho", ItemEffectType.KNOWLEDGE, 2, "INT:Engenharia", ItemEffectCondition.WIELDED, "+2 em Engenharia."),
        ),
        GemDefinition(
            ItemPart("gema_vigilia", "Gema de Vigília", "Gema", 2, 45, durability = 4, effect = "+1 em Sentidos.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_vigilia", ItemEffectType.KNOWLEDGE, 1, "POD:Sentidos", ItemEffectCondition.WIELDED, "+1 em Sentidos."),
        ),
        GemDefinition(
            ItemPart("gema_lamina_onirica", "Gema de Lâmina Onírica", "Gema", 3, 90, durability = 5, effect = "+1 de dano mágico.", materialTier = "UNCOMMON", characterCreationVisible = true),
            GemTier.UNCOMMON,
            ItemEffect("gema_lamina_onirica", ItemEffectType.MAGIC_DAMAGE, 1, "damage", ItemEffectCondition.WIELDED, "+1 de dano mágico."),
        ),
        GemDefinition(
            ItemPart("gema_mira_cintilante", "Gema de Mira Cintilante", "Gema", 2, 45, durability = 4, effect = "+1 em Ataque.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_mira_cintilante", ItemEffectType.ATTACK, 1, "attack", ItemEffectCondition.WIELDED, "+1 em Ataque."),
        ),
        GemDefinition(
            ItemPart("gema_impacto_rubro", "Gema de Impacto Rubro", "Gema", 5, 250, durability = 6, effect = "+2 de dano físico.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_impacto_rubro", ItemEffectType.PHYSICAL_DAMAGE, 2, "damage", ItemEffectCondition.WIELDED, "+2 de dano físico."),
        ),
        GemDefinition(
            ItemPart("gema_corte_fantasma", "Gema de Corte Fantasma", "Gema", 5, 250, durability = 6, effect = "+1 Categoria de Dado no dano.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_corte_fantasma", ItemEffectType.DIE_CATEGORY, 1, "damage", ItemEffectCondition.WIELDED, "+1 Categoria de Dado no dano."),
        ),
        GemDefinition(
            ItemPart("gema_ruina_ancestral", "Gema de Ruína Ancestral", "Gema", 8, 600, durability = 8, effect = "+3 de dano mágico.", materialTier = "ANCESTRAL", characterCreationVisible = false),
            GemTier.ANCESTRAL,
            ItemEffect("gema_ruina_ancestral", ItemEffectType.MAGIC_DAMAGE, 3, "damage", ItemEffectCondition.WIELDED, "+3 de dano mágico."),
        ),
        GemDefinition(
            ItemPart("gema_barreira", "Gema de Barreira", "Gema", 2, 45, durability = 4, effect = "+1 PG.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_barreira", ItemEffectType.PG, 1, "protection", ItemEffectCondition.EQUIPPED, "+1 PG."),
        ),
        GemDefinition(
            ItemPart("gema_bastiao", "Gema de Bastião", "Gema", 3, 90, durability = 5, effect = "+2 PL.", materialTier = "UNCOMMON", characterCreationVisible = true),
            GemTier.UNCOMMON,
            ItemEffect("gema_bastiao", ItemEffectType.PL, 2, "protection", ItemEffectCondition.EQUIPPED, "+2 PL."),
        ),
        GemDefinition(
            ItemPart("gema_resistencia", "Gema de Resistência", "Gema", 5, 250, durability = 6, effect = "Redução de Dano 1.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_resistencia", ItemEffectType.DAMAGE_REDUCTION, 1, "all", ItemEffectCondition.EQUIPPED, "Redução de Dano 1."),
        ),
        GemDefinition(
            ItemPart("gema_integridade", "Gema de Integridade", "Gema", 2, 45, durability = 4, effect = "+2 de Durabilidade máxima.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_integridade", ItemEffectType.DURABILITY, 2, "durability", ItemEffectCondition.WIELDED, "+2 de Durabilidade máxima."),
        ),
        GemDefinition(
            ItemPart("gema_escudo_solido", "Gema de Escudo Sólido", "Gema", 8, 600, durability = 8, effect = "+3 PG.", materialTier = "ANCESTRAL", characterCreationVisible = false),
            GemTier.ANCESTRAL,
            ItemEffect("gema_escudo_solido", ItemEffectType.PG, 3, "protection", ItemEffectCondition.EQUIPPED, "+3 PG."),
        ),
        GemDefinition(
            ItemPart("gema_pulso", "Gema de Pulso", "Gema", 3, 90, durability = 5, effect = "Com uma Ação, empurre um alvo próximo em 1 quadrado.", materialTier = "UNCOMMON", characterCreationVisible = true),
            GemTier.UNCOMMON,
            ItemEffect("gema_pulso", ItemEffectType.GEM_POWER, 0, "push", ItemEffectCondition.WIELDED, "Com uma Ação, empurre um alvo próximo em 1 quadrado."),
        ),
        GemDefinition(
            ItemPart("gema_veu", "Gema de Véu", "Gema", 5, 250, durability = 6, effect = "Com uma Ação, fique obscurecido até seu próximo turno.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_veu", ItemEffectType.GEM_POWER, 0, "veil", ItemEffectCondition.WIELDED, "Com uma Ação, fique obscurecido até seu próximo turno."),
        ),
        GemDefinition(
            ItemPart("gema_eco", "Gema de Eco", "Gema", 5, 250, durability = 6, effect = "Com uma Ação, repita o último som ouvido.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_eco", ItemEffectType.GEM_POWER, 0, "echo", ItemEffectCondition.WIELDED, "Com uma Ação, repita o último som ouvido."),
        ),
        GemDefinition(
            ItemPart("gema_restauro", "Gema de Restauro", "Gema", 5, 250, durability = 6, effect = "Com uma Ação, restaure 1 de Durabilidade do item.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_restauro", ItemEffectType.GEM_POWER, 0, "repair", ItemEffectCondition.WIELDED, "Com uma Ação, restaure 1 de Durabilidade do item."),
        ),
        GemDefinition(
            ItemPart("gema_portal_breve", "Gema de Portal Breve", "Gema", 8, 600, durability = 8, effect = "Com uma Ação, desloque-se até 3 quadrados visíveis.", materialTier = "ANCESTRAL", characterCreationVisible = false),
            GemTier.ANCESTRAL,
            ItemEffect("gema_portal_breve", ItemEffectType.GEM_POWER, 0, "teleport", ItemEffectCondition.WIELDED, "Com uma Ação, desloque-se até 3 quadrados visíveis."),
        ),
        GemDefinition(
            ItemPart("gema_luz", "Gema de Luz", "Gema", 2, 45, durability = 4, effect = "Com uma Ação, ilumine a área próxima.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_luz", ItemEffectType.RULE, 0, "light", ItemEffectCondition.WIELDED, "Com uma Ação, ilumine a área próxima."),
        ),
        GemDefinition(
            ItemPart("gema_bussola", "Gema de Bússola", "Gema", 2, 45, durability = 4, effect = "Aponta para um destino gravado ao ser instalada.", materialTier = "COMMON", characterCreationVisible = true),
            GemTier.COMMON,
            ItemEffect("gema_bussola", ItemEffectType.RULE, 0, "direction", ItemEffectCondition.WIELDED, "Aponta para um destino gravado ao ser instalada."),
        ),
        GemDefinition(
            ItemPart("gema_memoria", "Gema de Memória", "Gema", 3, 90, durability = 5, effect = "Armazena e reproduz uma lembrança sensorial.", materialTier = "UNCOMMON", characterCreationVisible = true),
            GemTier.UNCOMMON,
            ItemEffect("gema_memoria", ItemEffectType.RULE, 0, "memory", ItemEffectCondition.WIELDED, "Armazena e reproduz uma lembrança sensorial."),
        ),
        GemDefinition(
            ItemPart("gema_chave", "Gema de Chave", "Gema", 5, 250, durability = 6, effect = "Pode ser vinculada a um mecanismo como chave onírica.", materialTier = "RARE", characterCreationVisible = true),
            GemTier.RARE,
            ItemEffect("gema_chave", ItemEffectType.RULE, 0, "key", ItemEffectCondition.WIELDED, "Pode ser vinculada a um mecanismo como chave onírica."),
        ),
        GemDefinition(
            ItemPart("gema_oraculo", "Gema de Oráculo", "Gema", 8, 600, durability = 8, effect = "Com uma Ação, revela energia onírica próxima.", materialTier = "ANCESTRAL", characterCreationVisible = false),
            GemTier.ANCESTRAL,
            ItemEffect("gema_oraculo", ItemEffectType.RULE, 0, "oracle", ItemEffectCondition.WIELDED, "Com uma Ação, revela energia onírica próxima."),
        ),
    )
    fun effect(id: String) = entries.firstOrNull { it.part.id == id }?.effect
}
