#!/usr/bin/env python3
"""Generate structured material and item-trait models from canonical catalogs."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "app/src/main/java/com/kinderman/sdo/domain/catalog/GeneratedStructuredItemCatalog.kt"


def quote(value):
    return json.dumps(value, ensure_ascii=False).replace("$", "\\$")


def list_of(values):
    return "listOf(" + ", ".join(quote(value) for value in values) + ")"


def effect(value):
    return (
        "StructuredMaterialEffect("
        f"durability = {value.get('durability', 0)}, "
        f"damageBonus = {value.get('damageBonus', 0)}, "
        f"damageReduction = {value.get('damageReduction', 0)}, "
        f"pg = {value.get('pg', 0)}, "
        f"pl = {value.get('pl', 0)}, "
        f"categoryDieShift = {value.get('categoryDieShift', 0)}, "
        f"agilityLimit = {value.get('agilityLimit', 'null')}, "
        f"traitIds = {list_of(value.get('traitIds', []))})"
    )


def generate(materials, traits, economy):
    costs = {entry["id"]: entry for entry in economy["costs"]}
    lines = [
        "// Generated by tools/generate_structured_item_catalog.py. Do not edit.",
        "package com.kinderman.sdo.domain.catalog",
        "",
        "internal enum class MaterialTier { COMMON, UNCOMMON, RARE, ANCESTRAL }",
        "internal data class StructuredItemTrait(val id: String, val name: String, val description: String, val appliesTo: List<String>, val characterCreationVisible: Boolean, val ancestral: Boolean)",
        "internal data class StructuredMaterialEffect(val durability: Int, val damageBonus: Int, val damageReduction: Int, val pg: Int, val pl: Int, val categoryDieShift: Int, val agilityLimit: Int?, val traitIds: List<String>)",
        "internal data class StructuredMaterial(val id: String, val name: String, val tier: MaterialTier, val origins: List<String>, val characterCreationVisible: Boolean, val money: Int, val ph: Int, val weapon: StructuredMaterialEffect, val armor: StructuredMaterialEffect)",
        "",
        "internal object GeneratedStructuredItemCatalog {",
        "    val traits = listOf(",
    ]
    for trait in traits["traits"]:
        lines.append(
            "        StructuredItemTrait("
            f"{quote(trait['id'])}, {quote(trait['name'])}, {quote(trait['description'])}, {list_of(trait['appliesTo'])}, "
            f"{str(trait['characterCreationVisible']).lower()}, {str(trait.get('ancestral', False)).lower()}),"
        )
    lines.extend(("    )", "", "    val materials = listOf("))
    for material in materials["materials"]:
        cost = costs[material["id"]]
        lines.append(
            "        StructuredMaterial("
            f"{quote(material['id'])}, {quote(material['name'])}, MaterialTier.{material['tier']}, "
            f"{list_of(material['origins'])}, {str(material['characterCreationVisible']).lower()}, "
            f"{cost['money']}, {cost['ph']}, {effect(material['effects']['weapon'])}, {effect(material['effects']['armor'])}),"
        )
    lines.extend(("    )", "}", ""))
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    materials = json.loads((ROOT / "catalogs/materials.json").read_text())
    traits = json.loads((ROOT / "catalogs/item_traits.json").read_text())
    economy = json.loads((ROOT / "catalogs/item_economy.json").read_text())
    generated = generate(materials, traits, economy)
    if args.check:
        assert OUTPUT.read_text() == generated, "GeneratedStructuredItemCatalog.kt differs from canonical JSON"
    else:
        OUTPUT.write_text(generated)
    print(f"{len(materials['materials'])} structured materials and {len(traits['traits'])} traits generated")
