#!/usr/bin/env python3
"""Generate Kotlin item-part adapters from the canonical JSON catalogs."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def quote(value):
    return json.dumps(value, ensure_ascii=False).replace('$', '\\$')


def item_part(entry, group=None):
    creation_cost = "null" if entry["creationCost"] is None else str(entry["creationCost"])
    agility_limit = "null" if entry.get("agilityLimit") is None else str(entry["agilityLimit"])
    effect = entry.get("effect", "")
    if isinstance(effect, dict):
        effect = effect["description"]
    return (
        "ItemPart("
        f'{quote(entry["id"])}, {quote(entry["name"])}, {quote(group or entry["group"])}, '
        f'{creation_cost}, {entry["price"]}, {entry.get("load", 0)}, {entry.get("durability", 0)}, '
        f'{quote(entry.get("region", ""))}, {quote(effect)}, {entry.get("pg", 0)}, '
        f'{entry.get("pl", 0)}, {agility_limit})'
    )


def kotlin(items, modifications):
    grouped = {kind: [] for kind in ("WEAPON_MATERIAL", "ARMOR_MATERIAL", "WEAPON_BASE", "ARMOR_BASE")}
    catalog_items = []
    for entry in items["entries"]:
        if entry["kind"] == "CATALOG_ITEM":
            catalog_items.append(entry)
        else:
            grouped[entry["kind"]].append(entry)
    weapon_mods = []
    armor_mods = []
    for entry in modifications["entries"]:
        types = entry["compatibleItemTypes"]
        if "Arma" in types:
            weapon_mods.append(entry)
        if any(item_type in types for item_type in ("Armadura", "Acessório", "Escudo")):
            armor_mods.append(entry)

    sections = (
        ("weaponMaterials", grouped["WEAPON_MATERIAL"], None),
        ("armorMaterials", grouped["ARMOR_MATERIAL"], None),
        ("weaponBases", grouped["WEAPON_BASE"], None),
        ("armorBases", grouped["ARMOR_BASE"], None),
        ("weaponModifications", weapon_mods, "Modificação de arma"),
        ("armorModifications", armor_mods, "Modificação de armadura"),
    )
    lines = [
        "// Generated by tools/generate_item_catalog.py. Do not edit.",
        "package com.kinderman.sdo.domain.catalog",
        "",
        "import com.kinderman.sdo.domain.model.ItemPart",
        "import com.kinderman.sdo.domain.model.CatalogEntry",
        "import com.kinderman.sdo.domain.model.CatalogKind",
        "",
        "internal object GeneratedItemParts {",
    ]
    for name, entries, group in sections:
        lines.append(f"    val {name} = listOf(")
        lines.extend(f"        {item_part(entry, group)}," for entry in entries)
        lines.append("    )")
        lines.append("")
    lines.append("    private val modificationBaseGroups = mapOf(")
    for entry in modifications["entries"]:
        groups = ", ".join(quote(value) for value in entry.get("compatibleBaseGroups", []))
        lines.append(f'        {quote(entry["id"])} to setOf({groups}),')
    lines.append("    )")
    lines.append("    private val modificationBaseIds = mapOf(")
    for entry in modifications["entries"]:
        identifiers = ", ".join(quote(value) for value in entry.get("compatibleBaseIds", []))
        lines.append(f'        {quote(entry["id"])} to setOf({identifiers}),')
    lines.append("    )")
    lines.append("")
    lines.append("    val catalogItems = listOf(")
    for entry in catalog_items:
        cost = "null" if entry["creationCost"] is None else quote(str(entry["creationCost"]))
        lines.append(
            "        CatalogEntry("
            f'{quote(entry["id"])}, CatalogKind.ITEM, {quote(entry["name"])}, {quote(entry["group"])}, '
            f'{quote(entry["effect"])}, source = {quote(entry["source"])}, version = BuiltInCatalog.VERSION, '
            f'creationCost = {cost}, price = {entry["price"]}, load = {entry["load"]}, region = {quote(entry["region"])}, '
            f'ruleReference = {quote(entry["ruleReference"])}),'
        )
    lines.append("    )")
    lines.append("")
    lines.append("    fun modificationSupports(modificationId: String, base: ItemPart): Boolean {")
    lines.append("        val groups = modificationBaseGroups[modificationId].orEmpty()")
    lines.append("        val ids = modificationBaseIds[modificationId].orEmpty()")
    lines.append("        return (groups.isEmpty() && ids.isEmpty()) || base.group in groups || base.id in ids")
    lines.append("    }")
    lines.append("")
    lines.extend(("}", ""))
    return "\n".join(lines)


def validate(items, modifications):
    expected_kinds = {"WEAPON_MATERIAL", "ARMOR_MATERIAL", "WEAPON_BASE", "ARMOR_BASE"}
    assert {entry["kind"] for entry in items["entries"]} == expected_kinds | {"CATALOG_ITEM"}
    identifiers = [f'{entry["kind"]}:{entry["id"]}' for entry in items["entries"]]
    assert len(identifiers) == len(set(identifiers)), "duplicate item-part identifiers"
    modification_ids = [entry["id"] for entry in modifications["entries"]]
    assert len(modification_ids) == len(set(modification_ids)), "duplicate modification identifiers"
    for entry in items["entries"] + modifications["entries"]:
        for field in ("id", "name", "creationCost", "price", "load", "durability", "region", "pg", "pl", "agilityLimit"):
            assert field in entry, f'{entry.get("id", "unknown")} lacks typed field {field}'
    for entry in items["entries"]:
        if entry["kind"] == "CATALOG_ITEM":
            assert "source" in entry and "ruleReference" in entry
    for entry in modifications["entries"]:
        assert "compatibleBaseGroups" in entry and "compatibleBaseIds" in entry
        known_groups = {item["group"] for item in items["entries"] if item["kind"].endswith("_BASE")}
        known_ids = {item["id"] for item in items["entries"] if item["kind"].endswith("_BASE")}
        assert set(entry["compatibleBaseGroups"]) <= known_groups, f'{entry["id"]} has unknown base group'
        assert set(entry["compatibleBaseIds"]) <= known_ids, f'{entry["id"]} has unknown base id'


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    items_path = ROOT / "catalogs/items.json"
    modifications_path = ROOT / "catalogs/modifications.json"
    output_path = ROOT / "app/src/main/java/com/kinderman/sdo/domain/catalog/GeneratedItemParts.kt"
    items = json.loads(items_path.read_text())
    modifications = json.loads(modifications_path.read_text())
    validate(items, modifications)
    generated = kotlin(items, modifications)
    if args.check:
        assert output_path.read_text() == generated, "GeneratedItemParts.kt differs from canonical JSON"
    else:
        output_path.write_text(generated)
    print(f'{len(items["entries"])} bases/materials and {len(modifications["entries"])} modifications validated')
