#!/usr/bin/env python3
"""Validate the canonical JSON contract and generate Kotlin with no textual inference."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILES = ('powers', 'magic', 'ashes', 'runes', 'knowledge')
FIELDS = {
    'id': str, 'kind': str, 'name': str, 'group': str, 'summary': str,
    'cost': str, 'action': str, 'range': str, 'duration': str, 'source': str,
    'version': int, 'creationCost': str, 'price': int, 'load': int,
    'durability': str, 'region': str, 'relatedAttribute': str,
    'initialValue': (int, type(None)), 'prerequisites': list,
    'mechanicalEffect': str, 'ruleReference': str, 'keywords': list,
    'repeatable': bool, 'limit': str, 'activationCondition': str,
    'enhancements': str, 'deactivationCondition': str,
}
COUNTS = {'POWER': 100, 'MAGIC': 50, 'ASH': 50, 'RUNE': 50,
          'ACQUIRED_KNOWLEDGE': 50, 'ARCANE_KNOWLEDGE': 50, 'BATTLE_TECHNIQUE': 50}

def load_catalog(directory):
    entries = []
    for name in FILES:
        doc = json.loads((directory / f'{name}.json').read_text())
        assert doc['schemaVersion'] == 1
        for entry in doc['entries']:
            assert set(entry) == set(FIELDS), (entry.get('id'), 'fields')
            for key, expected in FIELDS.items():
                assert isinstance(entry[key], expected), (entry['id'], key)
                if expected is list:
                    assert all(isinstance(value, str) for value in entry[key])
            assert entry['version'] == doc['catalogVersion']
            for key in ('id', 'name', 'group', 'summary', 'source', 'mechanicalEffect', 'ruleReference'):
                assert entry[key].strip(), (entry['id'], key)
            if entry['kind'] in ('POWER', 'MAGIC', 'ASH', 'RUNE'):
                for key in ('cost', 'action', 'range', 'duration', 'activationCondition', 'deactivationCondition'):
                    assert entry[key].strip(), (entry['id'], key)
            else:
                assert entry['relatedAttribute'] in ('FOR', 'AGI', 'VIG', 'INT', 'POD', 'CAR')
                assert entry['initialValue'] == 1
                assert not entry['name'].lower().startswith('estudo de ')
            entries.append(entry)
    assert len({entry['id'] for entry in entries}) == len(entries), 'Duplicate IDs'
    assert {kind: sum(e['kind'] == kind for e in entries) for kind in COUNTS} == COUNTS
    return entries

def literal(value):
    if value is None: return 'null'
    if isinstance(value, bool): return str(value).lower()
    if isinstance(value, int): return str(value)
    if isinstance(value, list): return 'listOf(' + ', '.join(map(literal, value)) + ')'
    return json.dumps(value, ensure_ascii=False).replace('$', '\\$')

def render(entries):
    result = ['// Generated by tools/generate_catalog.py from catalogs/*.json. Do not edit.',
              'package com.kinderman.sdo.domain.catalog', '',
              'import com.kinderman.sdo.domain.model.CatalogEntry',
              'import com.kinderman.sdo.domain.model.CatalogKind', '',
              'internal object CanonicalCatalogData {']
    chunks = [entries[i:i + 20] for i in range(0, len(entries), 20)]
    result += ['    val entries: List<CatalogEntry> by lazy { ' + ' + '.join(f'part{i}()' for i in range(len(chunks))) + ' }']
    for index, chunk in enumerate(chunks):
        result += [f'    private fun part{index}(): List<CatalogEntry> = listOf(']
        for entry in chunk:
            args = [f'{key} = ' + ('CatalogKind.' + value if key == 'kind' else literal(value)) for key, value in entry.items()]
            result += ['        CatalogEntry(', *('            ' + arg + ',' for arg in args), '        ),']
        result += ['    )']
    return '\n'.join(result + ['}', ''])

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--catalog-dir', type=Path, default=ROOT / 'catalogs')
    args = parser.parse_args()
    entries = load_catalog(args.catalog_dir)
    output = ROOT / 'app/src/main/java/com/kinderman/sdo/domain/catalog/CanonicalCatalogData.kt'
    generated = render(entries)
    if args.check:
        assert output.read_text() == generated, 'Generated Kotlin differs from JSON. Run tools/generate_catalog.py.'
    else:
        output.write_text(generated)
    print(f'{len(entries)} structured records validated; Kotlin matches JSON.' if args.check else f'Generated {len(entries)} records.')
